Mere support for climateData API
LasseRegin/dmi-open-data pull request #3
Opened 2021-10-05 12:17 UTC by perabrahamsen

Hej Lasse.

Tak for et nyttigt stykke kode.

Jeg prøvede at kalde get_stations med en client åbnet med en "climateData"api key, det virkede ikke da get_stations er hardkodet til "metObs" api.  Jeg tror ikke man kan blande api key og api, så måske giver det mest mening at gemme navnet på api'en sammen med key i client datastrukturen?

Mvh,

Per

2021-10-05 14:31 UTC, perabrahamsen commented
Jeg tilføjede også 

    MeanRadiation = "mean_radiation"

til ClimateDataParameter som maglede fra listen.

Mvh,

Per

2021-10-06 12:12 UTC, perabrahamsen commented
Jeg tilføjede en "pars" parameter til get_closest_station, så man kan bede om den nærmeste station med specifikke data. Den bruger dog DMI navne, ikke navnene fra enums.py som den måske burde.

2021-10-17 17:23 UTC, LasseRegin requested changes
Tak for dine input. Har lige tilføjet et par foreslåede ændringer, så kodestilen matcher det eksisterende kode.

2021-10-17 17:23 UTC, LasseRegin commented on dmi_open_data/client.py
> +            self, limit: Optional[int] = 10000, offset: Optional[int] = 0
```suggestion
        self, limit: Optional[int] = 10000, offset: Optional[int] = 0
```

2021-10-17 17:23 UTC, LasseRegin commented on dmi_open_data/client.py
> +            pars = []
```suggestion
        self, latitude: float, longitude: float,
        pars: List[str] = []
```

2021-10-17 17:23 UTC, LasseRegin commented on dmi_open_data/client.py
> +        want_pars = set (pars)
```suggestion
        want_pars = set(pars)
```

2021-10-17 17:23 UTC, LasseRegin commented on dmi_open_data/client.py
> +            has_pars = set (station['properties']['parameterId'])
```suggestion
            has_pars = set(station["properties"]["parameterId"])
```

2021-10-17 17:23 UTC, LasseRegin commented on dmi_open_data/client.py
> +            if (not want_pars.issubset (has_pars)):
```suggestion
            if (not want_pars.issubset(has_pars)):
```

2021-10-18 10:24 UTC, perabrahamsen commented
Rettet.

2021-10-18 10:25 UTC, perabrahamsen commented
Tror jeg.  Jeg har stadig ikke lært hvordan github fungerer.

2025-10-14 18:40 UTC, LasseRegin commented
Closing PR as this was eventually implemented directly into the master branch. Thank you @perabrahamsen for the contribution.

2025-10-14 18:40 UTC, closed without merging